CREATE TABLE IF NOT EXISTS PORTFOLIO(id IDENTITY PRIMARY KEY, title VARCHAR);
DELETE FROM PORTFOLIO;
INSERT INTO PORTFOLIO VALUES(1, 'Bitfinex');
INSERT INTO PORTFOLIO VALUES(2, 'Bittrex');
INSERT INTO PORTFOLIO VALUES(3, 'Binance');